### ISSUE TITLE
loading example while running leads to inconsistent state

### ISSUE THREAD

**Issue by Entkenntnis** [andipaetzold/robotkarol.dev#987]
steps to reproduce:

1. start example
2. select another example
3. stop program
4. start program

expected behaviour: starting new example with matching world

actual behaviour: new program starts with world of previous example

workaround: stop program before selecting another example

**Comment by andipaetzold** [comment]
Hey @Entkenntnis,

thanks for reporting!
I just released an update and the program is now stopped before loading the example.

**Comment by Entkenntnis** [comment]
@andipaetzold Thanks for the quick reply.

Unfortunately, your fix breaks loading of examples :( There is an error in the console, and it looks like linked to your fix.

**Comment by andipaetzold** [comment]
If I understood my code... :shrug: 

So - bug fix attempt no. 2 :crossed_fingers:
